#!/usr/bin/env bash

# Script to display Azure Container Instance command help

echo "Azure Container Instance Management Command List"
echo "==========================================="
echo ""
echo "Basic Commands:"
echo "  pnpm run azure:container:create [env_suffix]        - Create a new container"
echo "  pnpm run azure:container:list                       - List containers"
echo "  pnpm run azure:container:log [-f] [container_name]  - Show container logs"
echo "  pnpm run azure:container:log:follow [container_name] - Follow container logs"
echo "  pnpm run azure:container:status [container_name]    - Show container status details"
echo "  pnpm run azure:container:delete [container_name]    - Delete a container"
echo ""
echo "Log Command Options:"
echo "  -f, --follow  - Follow logs in real time (same as Docker -f)"
echo ""
echo "Examples:"
echo "  # Create a container for development environment"
echo "  pnpm run azure:container:create dev"
echo ""
echo "  # List all containers"
echo "  pnpm run azure:container:list"
echo ""
echo "  # Show logs for a specific container"
echo "  pnpm run azure:container:log paperwave-dev-20250101-120000"
echo ""
echo "  # Follow logs for a specific container in real time"
echo "  pnpm run azure:container:log -f paperwave-dev-20250101-120000"
echo ""
echo "  # Use selection UI to follow logs"
echo "  pnpm run azure:container:log -f"
echo ""
echo "  # Log follow alias"
echo "  pnpm run azure:container:log:follow paperwave-dev-20250101-120000"
echo "  pnpm run azure:container:log:follow  # Selection UI"
echo ""
echo "  # Show status for a specific container"
echo "  pnpm run azure:container:status paperwave-dev-20250101-120000"
echo ""
echo "  # Delete a specific container"
echo "  pnpm run azure:container:delete paperwave-dev-20250101-120000"
echo ""
echo "Notes:"
echo "  • AZURE_RESOURCE_GROUP must be set in the .env file"
echo "  • If container name is not specified, a selection UI will be displayed"
echo "  • If there is only one container, it will be selected automatically"
echo "  • Azure CLI (az) must be installed and logged in"
echo ""
echo "Configuration Check:"
echo "  • Azure CLI: $(which az 2>/dev/null || echo 'Not installed')"
if [ -f ".env" ]; then
  AZURE_RESOURCE_GROUP=$(grep "AZURE_RESOURCE_GROUP" .env | cut -d '=' -f2 | tr -d '"')
  echo "  • Resource Group: ${AZURE_RESOURCE_GROUP:-'Not set'}"
else
  echo "  • Resource Group: .env file not found"
fi 